name: Deploy angular app to GitHub Pages
on: 
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: 'deploy-pages'
  cancel-in-progress: true

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Run Python script
        run: python backend/python/scrapVideos.py

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build 

      - name: Add 404 for SPA routing
        run: cp dist/angular-yt-live/browser/index.html dist/angular-yt-live/browser/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: ./dist/angular-yt-live/browser
  
  deploy: 
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5.0.0